// ============================================================================
//  Copyright (c) 2026 Chang Wei
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
//
// ----------------------------------------------------------------------------
//  File        : i486_dec_uop_stage.sv
//  Author      : Chang Wei <changwei1006@gmail.com>
//  Description : Combined decode + micro-op stage (stage_2_dec + stage_3_uop)
// ============================================================================

`include "openx86_defs.h.sv"

module i486_dec_uop_stage (
    input  logic [15: 0][ 7: 0] i_ifu_instruction,
    input  logic                i_ifu_instruction_valid,
    input  logic                i_ifu_segment_fault,
    input  logic [ 4: 0]        i_ifu_fifo_count,
    input  logic [31: 0]        i_ifu_eip,
    output logic                o_ifu_dec_ready,
    output logic                o_ifu_dec_fire,
    output logic [ 3: 0]        o_ifu_dec_consume_bytes,
    output logic                o_ifu_dec_error,
    input  logic                i_uop_flush,
    output logic                o_uop_valid,
    output micro_op_t           o_uop,
    input  logic                i_reg_ready,
    input  logic                clk,
    input  logic                rst_n
);

    logic [ 2: 0]      w_dec_base_reg_index;
    logic              w_dec_base_reg_is_present;
    logic [31: 0]      w_dec_displacement;
    logic [31: 0]      w_dec_immediate;
    logic [ 2: 0]      w_dec_index_reg_index;
    logic              w_dec_index_reg_is_present;
    logic [ 1: 0]      w_dec_modrm_mod;
    logic [ 2: 0]      w_dec_segment_reg_index;
    logic [ 1: 0]      w_dec_sib_scale_factor;
    logic [ 2: 0]      w_eee;
    logic              w_opcode_aaa;
    logic              w_opcode_aad;
    logic              w_opcode_aam;
    logic              w_opcode_aas;
    logic              w_opcode_adc_imm_to_acc;
    logic              w_opcode_adc_imm_to_reg_mem;
    logic              w_opcode_adc_reg_mem_to_reg;
    logic              w_opcode_adc_reg_to_reg_mem;
    logic              w_opcode_add_imm_to_acc;
    logic              w_opcode_add_imm_to_reg_mem;
    logic              w_opcode_add_reg_mem_to_reg;
    logic              w_opcode_add_reg_to_reg_mem;
    logic              w_opcode_and_imm_to_acc;
    logic              w_opcode_and_imm_to_reg_mem;
    logic              w_opcode_and_reg_mem_to_reg;
    logic              w_opcode_and_reg_to_reg_mem;
    logic              w_opcode_arpl;
    logic              w_opcode_bound;
    logic              w_opcode_bsf;
    logic              w_opcode_bsr;
    logic              w_opcode_bswap;
    logic              w_opcode_bt_imm;
    logic              w_opcode_bt_reg;
    logic              w_opcode_btc_imm;
    logic              w_opcode_btc_reg;
    logic              w_opcode_btr_imm;
    logic              w_opcode_btr_reg;
    logic              w_opcode_bts_imm;
    logic              w_opcode_bts_reg;
    logic              w_opcode_call_far_direct;
    logic              w_opcode_call_far_indirect;
    logic              w_opcode_call_near_direct;
    logic              w_opcode_call_near_indirect;
    logic              w_opcode_cbw;
    logic              w_opcode_cdq;
    logic              w_opcode_clc;
    logic              w_opcode_cld;
    logic              w_opcode_cli;
    logic              w_opcode_clts;
    logic              w_opcode_cmc;
    logic              w_opcode_cmp_imm_acc;
    logic              w_opcode_cmp_imm_reg_mem;
    logic              w_opcode_cmp_mem_reg;
    logic              w_opcode_cmp_reg_mem;
    logic              w_opcode_cmps;
    logic              w_opcode_cmpxchg;
    logic              w_opcode_cpuid;
    logic              w_opcode_cwd;
    logic              w_opcode_cwde;
    logic              w_opcode_daa;
    logic              w_opcode_das;
    logic              w_opcode_dec_reg;
    logic              w_opcode_dec_reg_mem;
    logic              w_opcode_div;
    logic              w_opcode_hlt;
    logic              w_opcode_idiv;
    logic              w_opcode_imul_acc;
    logic              w_opcode_imul_imm;
    logic              w_opcode_imul_reg;
    logic              w_opcode_in_fixed;
    logic              w_opcode_in_var;
    logic              w_opcode_inc_reg;
    logic              w_opcode_inc_reg_mem;
    logic              w_opcode_ins;
    logic              w_opcode_int_3;
    logic              w_opcode_int_4;
    logic              w_opcode_int_n;
    logic              w_opcode_invd;
    logic              w_opcode_invlpg;
    logic              w_opcode_invpcid;
    logic              w_opcode_iret;
    logic              w_opcode_jcc_near;
    logic              w_opcode_jcc_short;
    logic              w_opcode_jcxz;
    logic              w_opcode_jmp_far_direct;
    logic              w_opcode_jmp_far_indirect;
    logic              w_opcode_jmp_near_direct;
    logic              w_opcode_jmp_near_indirect;
    logic              w_opcode_jmp_short;
    logic              w_opcode_lahf;
    logic              w_opcode_lar;
    logic              w_opcode_lds;
    logic              w_opcode_lea;
    logic              w_opcode_leave;
    logic              w_opcode_les;
    logic              w_opcode_lfs;
    logic              w_opcode_lgdt;
    logic              w_opcode_lgs;
    logic              w_opcode_lidt;
    logic              w_opcode_lldt;
    logic              w_opcode_lmsw;
    logic              w_opcode_lods;
    logic              w_opcode_loop;
    logic              w_opcode_loopnz;
    logic              w_opcode_loopz;
    logic              w_opcode_lsl;
    logic              w_opcode_lss;
    logic              w_opcode_ltr;
    logic              w_opcode_mov_acc_to_mem;
    logic              w_opcode_mov_cr_from_reg;
    logic              w_opcode_mov_dr_from_reg;
    logic              w_opcode_mov_imm_to_reg;
    logic              w_opcode_mov_imm_to_reg_mem;
    logic              w_opcode_mov_mem_to_acc;
    logic              w_opcode_mov_reg_from_cr;
    logic              w_opcode_mov_reg_from_dr;
    logic              w_opcode_mov_reg_from_tr;
    logic              w_opcode_mov_reg_mem_to_reg;
    logic              w_opcode_mov_reg_mem_to_sreg;
    logic              w_opcode_mov_reg_to_reg_mem;
    logic              w_opcode_mov_sreg_to_reg_mem;
    logic              w_opcode_mov_tr_from_reg;
    logic              w_opcode_movbe_mem_reg;
    logic              w_opcode_movbe_reg_mem;
    logic              w_opcode_movs;
    logic              w_opcode_movsx;
    logic              w_opcode_movzx;
    logic              w_opcode_mul;
    logic              w_opcode_neg;
    logic              w_opcode_nop;
    logic              w_opcode_nop_multibyte;
    logic              w_opcode_not;
    logic              w_opcode_or_imm_to_acc;
    logic              w_opcode_or_imm_to_reg_mem;
    logic              w_opcode_or_reg_mem_to_reg;
    logic              w_opcode_or_reg_to_reg_mem;
    logic              w_opcode_out_fixed;
    logic              w_opcode_out_var;
    logic              w_opcode_outs;
    logic              w_opcode_pop_reg;
    logic              w_opcode_pop_reg_mem;
    logic              w_opcode_pop_sreg_2;
    logic              w_opcode_pop_sreg_3;
    logic              w_opcode_popa;
    logic              w_opcode_popf;
    logic              w_opcode_push_imm;
    logic              w_opcode_push_reg;
    logic              w_opcode_push_reg_mem;
    logic              w_opcode_push_sreg_2;
    logic              w_opcode_push_sreg_3;
    logic              w_opcode_pusha;
    logic              w_opcode_pushf;
    logic              w_opcode_rcl_1;
    logic              w_opcode_rcl_cl;
    logic              w_opcode_rcl_imm;
    logic              w_opcode_rcr_1;
    logic              w_opcode_rcr_cl;
    logic              w_opcode_rcr_imm;
    logic              w_opcode_rdmsr;
    logic              w_opcode_rdpmc;
    logic              w_opcode_rdtsc;
    logic              w_opcode_rdtscp;
    logic              w_opcode_ret_far;
    logic              w_opcode_ret_far_imm;
    logic              w_opcode_ret_near;
    logic              w_opcode_ret_near_imm;
    logic              w_opcode_rol_1;
    logic              w_opcode_rol_cl;
    logic              w_opcode_rol_imm;
    logic              w_opcode_ror_1;
    logic              w_opcode_ror_cl;
    logic              w_opcode_ror_imm;
    logic              w_opcode_rsm;
    logic              w_opcode_sahf;
    logic              w_opcode_sar_1;
    logic              w_opcode_sar_cl;
    logic              w_opcode_sar_imm;
    logic              w_opcode_sbb_imm_to_acc;
    logic              w_opcode_sbb_imm_to_reg_mem;
    logic              w_opcode_sbb_reg_mem_to_reg;
    logic              w_opcode_sbb_reg_to_reg_mem;
    logic              w_opcode_scas;
    logic              w_opcode_setcc;
    logic              w_opcode_sgdt;
    logic              w_opcode_shl_1;
    logic              w_opcode_shl_cl;
    logic              w_opcode_shl_imm;
    logic              w_opcode_shld_cl;
    logic              w_opcode_shld_imm;
    logic              w_opcode_shr_1;
    logic              w_opcode_shr_cl;
    logic              w_opcode_shr_imm;
    logic              w_opcode_shrd_cl;
    logic              w_opcode_shrd_imm;
    logic              w_opcode_sidt;
    logic              w_opcode_sldt;
    logic              w_opcode_smsw;
    logic              w_opcode_stc;
    logic              w_opcode_std;
    logic              w_opcode_sti;
    logic              w_opcode_stos;
    logic              w_opcode_str;
    logic              w_opcode_sub_imm_to_acc;
    logic              w_opcode_sub_imm_to_reg_mem;
    logic              w_opcode_sub_reg_mem_to_reg;
    logic              w_opcode_sub_reg_to_reg_mem;
    logic              w_opcode_test_imm_acc;
    logic              w_opcode_test_imm_reg_mem;
    logic              w_opcode_test_reg_mem;
    logic              w_opcode_ud0;
    logic              w_opcode_ud1;
    logic              w_opcode_ud2;
    logic              w_opcode_verr;
    logic              w_opcode_verw;
    logic              w_opcode_wait;
    logic              w_opcode_wbinvd;
    logic              w_opcode_wrmsr;
    logic              w_opcode_x87_esc;
    logic              w_opcode_mmx_any;
    logic              w_opcode_mmx_emms;
    logic              w_opcode_sse_any;
    logic              w_opcode_xadd;
    logic              w_opcode_xchg_acc;
    logic              w_opcode_xchg_reg_mem;
    logic              w_opcode_xlat;
    logic              w_opcode_xor_imm_to_acc;
    logic              w_opcode_xor_imm_to_reg_mem;
    logic              w_opcode_xor_reg_mem_to_reg;
    logic              w_opcode_xor_reg_to_reg_mem;
    logic [ 3: 0]      w_tttn;

    logic uop_stage2_valid;
    logic uop_stage2_ready;

    stage_2_dec u_dec (
        .i_ifu_instruction        (i_ifu_instruction),
        .i_ifu_instruction_valid  (i_ifu_instruction_valid),
        .i_ifu_segment_fault      (i_ifu_segment_fault),
        .i_ifu_fifo_count         (i_ifu_fifo_count),
        .i_ifu_eip                (i_ifu_eip),
        .o_ifu_dec_ready          (o_ifu_dec_ready),
        .o_ifu_dec_fire           (o_ifu_dec_fire),
        .o_ifu_dec_consume_bytes  (o_ifu_dec_consume_bytes),
        .o_ifu_dec_error          (o_ifu_dec_error),
        .o_uop_stage2_valid       (uop_stage2_valid),
        .i_uop_stage2_ready       (uop_stage2_ready),
        .i_uop_flush              (i_uop_flush),
        .o_dec_base_reg_index                       (w_dec_base_reg_index),
        .o_dec_base_reg_is_present                  (w_dec_base_reg_is_present),
        .o_dec_displacement                         (w_dec_displacement),
        .o_dec_immediate                            (w_dec_immediate),
        .o_dec_index_reg_index                      (w_dec_index_reg_index),
        .o_dec_index_reg_is_present                 (w_dec_index_reg_is_present),
        .o_dec_modrm_mod                            (w_dec_modrm_mod),
        .o_dec_segment_reg_index                    (w_dec_segment_reg_index),
        .o_dec_sib_scale_factor                     (w_dec_sib_scale_factor),
        .o_eee                                      (w_eee),
        .o_opcode_aaa                               (w_opcode_aaa),
        .o_opcode_aad                               (w_opcode_aad),
        .o_opcode_aam                               (w_opcode_aam),
        .o_opcode_aas                               (w_opcode_aas),
        .o_opcode_adc_imm_to_acc                    (w_opcode_adc_imm_to_acc),
        .o_opcode_adc_imm_to_reg_mem                (w_opcode_adc_imm_to_reg_mem),
        .o_opcode_adc_reg_mem_to_reg                (w_opcode_adc_reg_mem_to_reg),
        .o_opcode_adc_reg_to_reg_mem                (w_opcode_adc_reg_to_reg_mem),
        .o_opcode_add_imm_to_acc                    (w_opcode_add_imm_to_acc),
        .o_opcode_add_imm_to_reg_mem                (w_opcode_add_imm_to_reg_mem),
        .o_opcode_add_reg_mem_to_reg                (w_opcode_add_reg_mem_to_reg),
        .o_opcode_add_reg_to_reg_mem                (w_opcode_add_reg_to_reg_mem),
        .o_opcode_and_imm_to_acc                    (w_opcode_and_imm_to_acc),
        .o_opcode_and_imm_to_reg_mem                (w_opcode_and_imm_to_reg_mem),
        .o_opcode_and_reg_mem_to_reg                (w_opcode_and_reg_mem_to_reg),
        .o_opcode_and_reg_to_reg_mem                (w_opcode_and_reg_to_reg_mem),
        .o_opcode_arpl                              (w_opcode_arpl),
        .o_opcode_bound                             (w_opcode_bound),
        .o_opcode_bsf                               (w_opcode_bsf),
        .o_opcode_bsr                               (w_opcode_bsr),
        .o_opcode_bswap                             (w_opcode_bswap),
        .o_opcode_bt_imm                            (w_opcode_bt_imm),
        .o_opcode_bt_reg                            (w_opcode_bt_reg),
        .o_opcode_btc_imm                           (w_opcode_btc_imm),
        .o_opcode_btc_reg                           (w_opcode_btc_reg),
        .o_opcode_btr_imm                           (w_opcode_btr_imm),
        .o_opcode_btr_reg                           (w_opcode_btr_reg),
        .o_opcode_bts_imm                           (w_opcode_bts_imm),
        .o_opcode_bts_reg                           (w_opcode_bts_reg),
        .o_opcode_call_far_direct                   (w_opcode_call_far_direct),
        .o_opcode_call_far_indirect                 (w_opcode_call_far_indirect),
        .o_opcode_call_near_direct                  (w_opcode_call_near_direct),
        .o_opcode_call_near_indirect                (w_opcode_call_near_indirect),
        .o_opcode_cbw                               (w_opcode_cbw),
        .o_opcode_cdq                               (w_opcode_cdq),
        .o_opcode_clc                               (w_opcode_clc),
        .o_opcode_cld                               (w_opcode_cld),
        .o_opcode_cli                               (w_opcode_cli),
        .o_opcode_clts                              (w_opcode_clts),
        .o_opcode_cmc                               (w_opcode_cmc),
        .o_opcode_cmp_imm_acc                       (w_opcode_cmp_imm_acc),
        .o_opcode_cmp_imm_reg_mem                   (w_opcode_cmp_imm_reg_mem),
        .o_opcode_cmp_mem_reg                       (w_opcode_cmp_mem_reg),
        .o_opcode_cmp_reg_mem                       (w_opcode_cmp_reg_mem),
        .o_opcode_cmps                              (w_opcode_cmps),
        .o_opcode_cmpxchg                           (w_opcode_cmpxchg),
        .o_opcode_cpuid                             (w_opcode_cpuid),
        .o_opcode_cwd                               (w_opcode_cwd),
        .o_opcode_cwde                              (w_opcode_cwde),
        .o_opcode_daa                               (w_opcode_daa),
        .o_opcode_das                               (w_opcode_das),
        .o_opcode_dec_reg                           (w_opcode_dec_reg),
        .o_opcode_dec_reg_mem                       (w_opcode_dec_reg_mem),
        .o_opcode_div                               (w_opcode_div),
        .o_opcode_hlt                               (w_opcode_hlt),
        .o_opcode_idiv                              (w_opcode_idiv),
        .o_opcode_imul_acc                          (w_opcode_imul_acc),
        .o_opcode_imul_imm                          (w_opcode_imul_imm),
        .o_opcode_imul_reg                          (w_opcode_imul_reg),
        .o_opcode_in_fixed                          (w_opcode_in_fixed),
        .o_opcode_in_var                            (w_opcode_in_var),
        .o_opcode_inc_reg                           (w_opcode_inc_reg),
        .o_opcode_inc_reg_mem                       (w_opcode_inc_reg_mem),
        .o_opcode_ins                               (w_opcode_ins),
        .o_opcode_int_3                             (w_opcode_int_3),
        .o_opcode_int_4                             (w_opcode_int_4),
        .o_opcode_int_n                             (w_opcode_int_n),
        .o_opcode_invd                              (w_opcode_invd),
        .o_opcode_invlpg                            (w_opcode_invlpg),
        .o_opcode_invpcid                           (w_opcode_invpcid),
        .o_opcode_iret                              (w_opcode_iret),
        .o_opcode_jcc_near                          (w_opcode_jcc_near),
        .o_opcode_jcc_short                         (w_opcode_jcc_short),
        .o_opcode_jcxz                              (w_opcode_jcxz),
        .o_opcode_jmp_far_direct                    (w_opcode_jmp_far_direct),
        .o_opcode_jmp_far_indirect                  (w_opcode_jmp_far_indirect),
        .o_opcode_jmp_near_direct                   (w_opcode_jmp_near_direct),
        .o_opcode_jmp_near_indirect                 (w_opcode_jmp_near_indirect),
        .o_opcode_jmp_short                         (w_opcode_jmp_short),
        .o_opcode_lahf                              (w_opcode_lahf),
        .o_opcode_lar                               (w_opcode_lar),
        .o_opcode_lds                               (w_opcode_lds),
        .o_opcode_lea                               (w_opcode_lea),
        .o_opcode_leave                             (w_opcode_leave),
        .o_opcode_les                               (w_opcode_les),
        .o_opcode_lfs                               (w_opcode_lfs),
        .o_opcode_lgdt                              (w_opcode_lgdt),
        .o_opcode_lgs                               (w_opcode_lgs),
        .o_opcode_lidt                              (w_opcode_lidt),
        .o_opcode_lldt                              (w_opcode_lldt),
        .o_opcode_lmsw                              (w_opcode_lmsw),
        .o_opcode_lods                              (w_opcode_lods),
        .o_opcode_loop                              (w_opcode_loop),
        .o_opcode_loopnz                            (w_opcode_loopnz),
        .o_opcode_loopz                             (w_opcode_loopz),
        .o_opcode_lsl                               (w_opcode_lsl),
        .o_opcode_lss                               (w_opcode_lss),
        .o_opcode_ltr                               (w_opcode_ltr),
        .o_opcode_mov_acc_to_mem                    (w_opcode_mov_acc_to_mem),
        .o_opcode_mov_cr_from_reg                   (w_opcode_mov_cr_from_reg),
        .o_opcode_mov_dr_from_reg                   (w_opcode_mov_dr_from_reg),
        .o_opcode_mov_imm_to_reg                    (w_opcode_mov_imm_to_reg),
        .o_opcode_mov_imm_to_reg_mem                (w_opcode_mov_imm_to_reg_mem),
        .o_opcode_mov_mem_to_acc                    (w_opcode_mov_mem_to_acc),
        .o_opcode_mov_reg_from_cr                   (w_opcode_mov_reg_from_cr),
        .o_opcode_mov_reg_from_dr                   (w_opcode_mov_reg_from_dr),
        .o_opcode_mov_reg_from_tr                   (w_opcode_mov_reg_from_tr),
        .o_opcode_mov_reg_mem_to_reg                (w_opcode_mov_reg_mem_to_reg),
        .o_opcode_mov_reg_mem_to_sreg               (w_opcode_mov_reg_mem_to_sreg),
        .o_opcode_mov_reg_to_reg_mem                (w_opcode_mov_reg_to_reg_mem),
        .o_opcode_mov_sreg_to_reg_mem               (w_opcode_mov_sreg_to_reg_mem),
        .o_opcode_mov_tr_from_reg                   (w_opcode_mov_tr_from_reg),
        .o_opcode_movbe_mem_reg                     (w_opcode_movbe_mem_reg),
        .o_opcode_movbe_reg_mem                     (w_opcode_movbe_reg_mem),
        .o_opcode_movs                              (w_opcode_movs),
        .o_opcode_movsx                             (w_opcode_movsx),
        .o_opcode_movzx                             (w_opcode_movzx),
        .o_opcode_mul                               (w_opcode_mul),
        .o_opcode_neg                               (w_opcode_neg),
        .o_opcode_nop                               (w_opcode_nop),
        .o_opcode_nop_multibyte                     (w_opcode_nop_multibyte),
        .o_opcode_not                               (w_opcode_not),
        .o_opcode_or_imm_to_acc                     (w_opcode_or_imm_to_acc),
        .o_opcode_or_imm_to_reg_mem                 (w_opcode_or_imm_to_reg_mem),
        .o_opcode_or_reg_mem_to_reg                 (w_opcode_or_reg_mem_to_reg),
        .o_opcode_or_reg_to_reg_mem                 (w_opcode_or_reg_to_reg_mem),
        .o_opcode_out_fixed                         (w_opcode_out_fixed),
        .o_opcode_out_var                           (w_opcode_out_var),
        .o_opcode_outs                              (w_opcode_outs),
        .o_opcode_pop_reg                           (w_opcode_pop_reg),
        .o_opcode_pop_reg_mem                       (w_opcode_pop_reg_mem),
        .o_opcode_pop_sreg_2                        (w_opcode_pop_sreg_2),
        .o_opcode_pop_sreg_3                        (w_opcode_pop_sreg_3),
        .o_opcode_popa                              (w_opcode_popa),
        .o_opcode_popf                              (w_opcode_popf),
        .o_opcode_push_imm                          (w_opcode_push_imm),
        .o_opcode_push_reg                          (w_opcode_push_reg),
        .o_opcode_push_reg_mem                      (w_opcode_push_reg_mem),
        .o_opcode_push_sreg_2                       (w_opcode_push_sreg_2),
        .o_opcode_push_sreg_3                       (w_opcode_push_sreg_3),
        .o_opcode_pusha                             (w_opcode_pusha),
        .o_opcode_pushf                             (w_opcode_pushf),
        .o_opcode_rcl_1                             (w_opcode_rcl_1),
        .o_opcode_rcl_cl                            (w_opcode_rcl_cl),
        .o_opcode_rcl_imm                           (w_opcode_rcl_imm),
        .o_opcode_rcr_1                             (w_opcode_rcr_1),
        .o_opcode_rcr_cl                            (w_opcode_rcr_cl),
        .o_opcode_rcr_imm                           (w_opcode_rcr_imm),
        .o_opcode_rdmsr                             (w_opcode_rdmsr),
        .o_opcode_rdpmc                             (w_opcode_rdpmc),
        .o_opcode_rdtsc                             (w_opcode_rdtsc),
        .o_opcode_rdtscp                            (w_opcode_rdtscp),
        .o_opcode_ret_far                           (w_opcode_ret_far),
        .o_opcode_ret_far_imm                       (w_opcode_ret_far_imm),
        .o_opcode_ret_near                          (w_opcode_ret_near),
        .o_opcode_ret_near_imm                      (w_opcode_ret_near_imm),
        .o_opcode_rol_1                             (w_opcode_rol_1),
        .o_opcode_rol_cl                            (w_opcode_rol_cl),
        .o_opcode_rol_imm                           (w_opcode_rol_imm),
        .o_opcode_ror_1                             (w_opcode_ror_1),
        .o_opcode_ror_cl                            (w_opcode_ror_cl),
        .o_opcode_ror_imm                           (w_opcode_ror_imm),
        .o_opcode_rsm                               (w_opcode_rsm),
        .o_opcode_sahf                              (w_opcode_sahf),
        .o_opcode_sar_1                             (w_opcode_sar_1),
        .o_opcode_sar_cl                            (w_opcode_sar_cl),
        .o_opcode_sar_imm                           (w_opcode_sar_imm),
        .o_opcode_sbb_imm_to_acc                    (w_opcode_sbb_imm_to_acc),
        .o_opcode_sbb_imm_to_reg_mem                (w_opcode_sbb_imm_to_reg_mem),
        .o_opcode_sbb_reg_mem_to_reg                (w_opcode_sbb_reg_mem_to_reg),
        .o_opcode_sbb_reg_to_reg_mem                (w_opcode_sbb_reg_to_reg_mem),
        .o_opcode_scas                              (w_opcode_scas),
        .o_opcode_setcc                             (w_opcode_setcc),
        .o_opcode_sgdt                              (w_opcode_sgdt),
        .o_opcode_shl_1                             (w_opcode_shl_1),
        .o_opcode_shl_cl                            (w_opcode_shl_cl),
        .o_opcode_shl_imm                           (w_opcode_shl_imm),
        .o_opcode_shld_cl                           (w_opcode_shld_cl),
        .o_opcode_shld_imm                          (w_opcode_shld_imm),
        .o_opcode_shr_1                             (w_opcode_shr_1),
        .o_opcode_shr_cl                            (w_opcode_shr_cl),
        .o_opcode_shr_imm                           (w_opcode_shr_imm),
        .o_opcode_shrd_cl                           (w_opcode_shrd_cl),
        .o_opcode_shrd_imm                          (w_opcode_shrd_imm),
        .o_opcode_sidt                              (w_opcode_sidt),
        .o_opcode_sldt                              (w_opcode_sldt),
        .o_opcode_smsw                              (w_opcode_smsw),
        .o_opcode_stc                               (w_opcode_stc),
        .o_opcode_std                               (w_opcode_std),
        .o_opcode_sti                               (w_opcode_sti),
        .o_opcode_stos                              (w_opcode_stos),
        .o_opcode_str                               (w_opcode_str),
        .o_opcode_sub_imm_to_acc                    (w_opcode_sub_imm_to_acc),
        .o_opcode_sub_imm_to_reg_mem                (w_opcode_sub_imm_to_reg_mem),
        .o_opcode_sub_reg_mem_to_reg                (w_opcode_sub_reg_mem_to_reg),
        .o_opcode_sub_reg_to_reg_mem                (w_opcode_sub_reg_to_reg_mem),
        .o_opcode_test_imm_acc                      (w_opcode_test_imm_acc),
        .o_opcode_test_imm_reg_mem                  (w_opcode_test_imm_reg_mem),
        .o_opcode_test_reg_mem                      (w_opcode_test_reg_mem),
        .o_opcode_ud0                               (w_opcode_ud0),
        .o_opcode_ud1                               (w_opcode_ud1),
        .o_opcode_ud2                               (w_opcode_ud2),
        .o_opcode_verr                              (w_opcode_verr),
        .o_opcode_verw                              (w_opcode_verw),
        .o_opcode_wait                              (w_opcode_wait),
        .o_opcode_wbinvd                            (w_opcode_wbinvd),
        .o_opcode_wrmsr                             (w_opcode_wrmsr),
        .o_opcode_x87_esc                           (w_opcode_x87_esc),
        .o_opcode_mmx_any                           (w_opcode_mmx_any),
        .o_opcode_mmx_emms                          (w_opcode_mmx_emms),
        .o_opcode_sse_any                           (w_opcode_sse_any),
        .o_opcode_xadd                              (w_opcode_xadd),
        .o_opcode_xchg_acc                          (w_opcode_xchg_acc),
        .o_opcode_xchg_reg_mem                      (w_opcode_xchg_reg_mem),
        .o_opcode_xlat                              (w_opcode_xlat),
        .o_opcode_xor_imm_to_acc                    (w_opcode_xor_imm_to_acc),
        .o_opcode_xor_imm_to_reg_mem                (w_opcode_xor_imm_to_reg_mem),
        .o_opcode_xor_reg_mem_to_reg                (w_opcode_xor_reg_mem_to_reg),
        .o_opcode_xor_reg_to_reg_mem                (w_opcode_xor_reg_to_reg_mem),
        .o_tttn                                     (w_tttn),
        .clk                      (clk),
        .rst_n                    (rst_n)
    );

    stage_3_uop u_uop (
        .i_dec_base_reg_index                       (w_dec_base_reg_index),
        .i_dec_base_reg_is_present                  (w_dec_base_reg_is_present),
        .i_dec_displacement                         (w_dec_displacement),
        .i_dec_immediate                            (w_dec_immediate),
        .i_dec_index_reg_index                      (w_dec_index_reg_index),
        .i_dec_index_reg_is_present                 (w_dec_index_reg_is_present),
        .i_dec_modrm_mod                            (w_dec_modrm_mod),
        .i_dec_segment_reg_index                    (w_dec_segment_reg_index),
        .i_dec_sib_scale_factor                     (w_dec_sib_scale_factor),
        .i_eee                                      (w_eee),
        .i_opcode_aaa                               (w_opcode_aaa),
        .i_opcode_aad                               (w_opcode_aad),
        .i_opcode_aam                               (w_opcode_aam),
        .i_opcode_aas                               (w_opcode_aas),
        .i_opcode_adc_imm_to_acc                    (w_opcode_adc_imm_to_acc),
        .i_opcode_adc_imm_to_reg_mem                (w_opcode_adc_imm_to_reg_mem),
        .i_opcode_adc_reg_mem_to_reg                (w_opcode_adc_reg_mem_to_reg),
        .i_opcode_adc_reg_to_reg_mem                (w_opcode_adc_reg_to_reg_mem),
        .i_opcode_add_imm_to_acc                    (w_opcode_add_imm_to_acc),
        .i_opcode_add_imm_to_reg_mem                (w_opcode_add_imm_to_reg_mem),
        .i_opcode_add_reg_mem_to_reg                (w_opcode_add_reg_mem_to_reg),
        .i_opcode_add_reg_to_reg_mem                (w_opcode_add_reg_to_reg_mem),
        .i_opcode_and_imm_to_acc                    (w_opcode_and_imm_to_acc),
        .i_opcode_and_imm_to_reg_mem                (w_opcode_and_imm_to_reg_mem),
        .i_opcode_and_reg_mem_to_reg                (w_opcode_and_reg_mem_to_reg),
        .i_opcode_and_reg_to_reg_mem                (w_opcode_and_reg_to_reg_mem),
        .i_opcode_arpl                              (w_opcode_arpl),
        .i_opcode_bound                             (w_opcode_bound),
        .i_opcode_bsf                               (w_opcode_bsf),
        .i_opcode_bsr                               (w_opcode_bsr),
        .i_opcode_bswap                             (w_opcode_bswap),
        .i_opcode_bt_imm                            (w_opcode_bt_imm),
        .i_opcode_bt_reg                            (w_opcode_bt_reg),
        .i_opcode_btc_imm                           (w_opcode_btc_imm),
        .i_opcode_btc_reg                           (w_opcode_btc_reg),
        .i_opcode_btr_imm                           (w_opcode_btr_imm),
        .i_opcode_btr_reg                           (w_opcode_btr_reg),
        .i_opcode_bts_imm                           (w_opcode_bts_imm),
        .i_opcode_bts_reg                           (w_opcode_bts_reg),
        .i_opcode_call_far_direct                   (w_opcode_call_far_direct),
        .i_opcode_call_far_indirect                 (w_opcode_call_far_indirect),
        .i_opcode_call_near_direct                  (w_opcode_call_near_direct),
        .i_opcode_call_near_indirect                (w_opcode_call_near_indirect),
        .i_opcode_cbw                               (w_opcode_cbw),
        .i_opcode_cdq                               (w_opcode_cdq),
        .i_opcode_clc                               (w_opcode_clc),
        .i_opcode_cld                               (w_opcode_cld),
        .i_opcode_cli                               (w_opcode_cli),
        .i_opcode_clts                              (w_opcode_clts),
        .i_opcode_cmc                               (w_opcode_cmc),
        .i_opcode_cmp_imm_acc                       (w_opcode_cmp_imm_acc),
        .i_opcode_cmp_imm_reg_mem                   (w_opcode_cmp_imm_reg_mem),
        .i_opcode_cmp_mem_reg                       (w_opcode_cmp_mem_reg),
        .i_opcode_cmp_reg_mem                       (w_opcode_cmp_reg_mem),
        .i_opcode_cmps                              (w_opcode_cmps),
        .i_opcode_cmpxchg                           (w_opcode_cmpxchg),
        .i_opcode_cpuid                             (w_opcode_cpuid),
        .i_opcode_cwd                               (w_opcode_cwd),
        .i_opcode_cwde                              (w_opcode_cwde),
        .i_opcode_daa                               (w_opcode_daa),
        .i_opcode_das                               (w_opcode_das),
        .i_opcode_dec_reg                           (w_opcode_dec_reg),
        .i_opcode_dec_reg_mem                       (w_opcode_dec_reg_mem),
        .i_opcode_div                               (w_opcode_div),
        .i_opcode_hlt                               (w_opcode_hlt),
        .i_opcode_idiv                              (w_opcode_idiv),
        .i_opcode_imul_acc                          (w_opcode_imul_acc),
        .i_opcode_imul_imm                          (w_opcode_imul_imm),
        .i_opcode_imul_reg                          (w_opcode_imul_reg),
        .i_opcode_in_fixed                          (w_opcode_in_fixed),
        .i_opcode_in_var                            (w_opcode_in_var),
        .i_opcode_inc_reg                           (w_opcode_inc_reg),
        .i_opcode_inc_reg_mem                       (w_opcode_inc_reg_mem),
        .i_opcode_ins                               (w_opcode_ins),
        .i_opcode_int_3                             (w_opcode_int_3),
        .i_opcode_int_4                             (w_opcode_int_4),
        .i_opcode_int_n                             (w_opcode_int_n),
        .i_opcode_invd                              (w_opcode_invd),
        .i_opcode_invlpg                            (w_opcode_invlpg),
        .i_opcode_invpcid                           (w_opcode_invpcid),
        .i_opcode_iret                              (w_opcode_iret),
        .i_opcode_jcc_near                          (w_opcode_jcc_near),
        .i_opcode_jcc_short                         (w_opcode_jcc_short),
        .i_opcode_jcxz                              (w_opcode_jcxz),
        .i_opcode_jmp_far_direct                    (w_opcode_jmp_far_direct),
        .i_opcode_jmp_far_indirect                  (w_opcode_jmp_far_indirect),
        .i_opcode_jmp_near_direct                   (w_opcode_jmp_near_direct),
        .i_opcode_jmp_near_indirect                 (w_opcode_jmp_near_indirect),
        .i_opcode_jmp_short                         (w_opcode_jmp_short),
        .i_opcode_lahf                              (w_opcode_lahf),
        .i_opcode_lar                               (w_opcode_lar),
        .i_opcode_lds                               (w_opcode_lds),
        .i_opcode_lea                               (w_opcode_lea),
        .i_opcode_leave                             (w_opcode_leave),
        .i_opcode_les                               (w_opcode_les),
        .i_opcode_lfs                               (w_opcode_lfs),
        .i_opcode_lgdt                              (w_opcode_lgdt),
        .i_opcode_lgs                               (w_opcode_lgs),
        .i_opcode_lidt                              (w_opcode_lidt),
        .i_opcode_lldt                              (w_opcode_lldt),
        .i_opcode_lmsw                              (w_opcode_lmsw),
        .i_opcode_lods                              (w_opcode_lods),
        .i_opcode_loop                              (w_opcode_loop),
        .i_opcode_loopnz                            (w_opcode_loopnz),
        .i_opcode_loopz                             (w_opcode_loopz),
        .i_opcode_lsl                               (w_opcode_lsl),
        .i_opcode_lss                               (w_opcode_lss),
        .i_opcode_ltr                               (w_opcode_ltr),
        .i_opcode_mov_acc_to_mem                    (w_opcode_mov_acc_to_mem),
        .i_opcode_mov_cr_from_reg                   (w_opcode_mov_cr_from_reg),
        .i_opcode_mov_dr_from_reg                   (w_opcode_mov_dr_from_reg),
        .i_opcode_mov_imm_to_reg                    (w_opcode_mov_imm_to_reg),
        .i_opcode_mov_imm_to_reg_mem                (w_opcode_mov_imm_to_reg_mem),
        .i_opcode_mov_mem_to_acc                    (w_opcode_mov_mem_to_acc),
        .i_opcode_mov_reg_from_cr                   (w_opcode_mov_reg_from_cr),
        .i_opcode_mov_reg_from_dr                   (w_opcode_mov_reg_from_dr),
        .i_opcode_mov_reg_from_tr                   (w_opcode_mov_reg_from_tr),
        .i_opcode_mov_reg_mem_to_reg                (w_opcode_mov_reg_mem_to_reg),
        .i_opcode_mov_reg_mem_to_sreg               (w_opcode_mov_reg_mem_to_sreg),
        .i_opcode_mov_reg_to_reg_mem                (w_opcode_mov_reg_to_reg_mem),
        .i_opcode_mov_sreg_to_reg_mem               (w_opcode_mov_sreg_to_reg_mem),
        .i_opcode_mov_tr_from_reg                   (w_opcode_mov_tr_from_reg),
        .i_opcode_movbe_mem_reg                     (w_opcode_movbe_mem_reg),
        .i_opcode_movbe_reg_mem                     (w_opcode_movbe_reg_mem),
        .i_opcode_movs                              (w_opcode_movs),
        .i_opcode_movsx                             (w_opcode_movsx),
        .i_opcode_movzx                             (w_opcode_movzx),
        .i_opcode_mul                               (w_opcode_mul),
        .i_opcode_neg                               (w_opcode_neg),
        .i_opcode_nop                               (w_opcode_nop),
        .i_opcode_nop_multibyte                     (w_opcode_nop_multibyte),
        .i_opcode_not                               (w_opcode_not),
        .i_opcode_or_imm_to_acc                     (w_opcode_or_imm_to_acc),
        .i_opcode_or_imm_to_reg_mem                 (w_opcode_or_imm_to_reg_mem),
        .i_opcode_or_reg_mem_to_reg                 (w_opcode_or_reg_mem_to_reg),
        .i_opcode_or_reg_to_reg_mem                 (w_opcode_or_reg_to_reg_mem),
        .i_opcode_out_fixed                         (w_opcode_out_fixed),
        .i_opcode_out_var                           (w_opcode_out_var),
        .i_opcode_outs                              (w_opcode_outs),
        .i_opcode_pop_reg                           (w_opcode_pop_reg),
        .i_opcode_pop_reg_mem                       (w_opcode_pop_reg_mem),
        .i_opcode_pop_sreg_2                        (w_opcode_pop_sreg_2),
        .i_opcode_pop_sreg_3                        (w_opcode_pop_sreg_3),
        .i_opcode_popa                              (w_opcode_popa),
        .i_opcode_popf                              (w_opcode_popf),
        .i_opcode_push_imm                          (w_opcode_push_imm),
        .i_opcode_push_reg                          (w_opcode_push_reg),
        .i_opcode_push_reg_mem                      (w_opcode_push_reg_mem),
        .i_opcode_push_sreg_2                       (w_opcode_push_sreg_2),
        .i_opcode_push_sreg_3                       (w_opcode_push_sreg_3),
        .i_opcode_pusha                             (w_opcode_pusha),
        .i_opcode_pushf                             (w_opcode_pushf),
        .i_opcode_rcl_1                             (w_opcode_rcl_1),
        .i_opcode_rcl_cl                            (w_opcode_rcl_cl),
        .i_opcode_rcl_imm                           (w_opcode_rcl_imm),
        .i_opcode_rcr_1                             (w_opcode_rcr_1),
        .i_opcode_rcr_cl                            (w_opcode_rcr_cl),
        .i_opcode_rcr_imm                           (w_opcode_rcr_imm),
        .i_opcode_rdmsr                             (w_opcode_rdmsr),
        .i_opcode_rdpmc                             (w_opcode_rdpmc),
        .i_opcode_rdtsc                             (w_opcode_rdtsc),
        .i_opcode_rdtscp                            (w_opcode_rdtscp),
        .i_opcode_ret_far                           (w_opcode_ret_far),
        .i_opcode_ret_far_imm                       (w_opcode_ret_far_imm),
        .i_opcode_ret_near                          (w_opcode_ret_near),
        .i_opcode_ret_near_imm                      (w_opcode_ret_near_imm),
        .i_opcode_rol_1                             (w_opcode_rol_1),
        .i_opcode_rol_cl                            (w_opcode_rol_cl),
        .i_opcode_rol_imm                           (w_opcode_rol_imm),
        .i_opcode_ror_1                             (w_opcode_ror_1),
        .i_opcode_ror_cl                            (w_opcode_ror_cl),
        .i_opcode_ror_imm                           (w_opcode_ror_imm),
        .i_opcode_rsm                               (w_opcode_rsm),
        .i_opcode_sahf                              (w_opcode_sahf),
        .i_opcode_sar_1                             (w_opcode_sar_1),
        .i_opcode_sar_cl                            (w_opcode_sar_cl),
        .i_opcode_sar_imm                           (w_opcode_sar_imm),
        .i_opcode_sbb_imm_to_acc                    (w_opcode_sbb_imm_to_acc),
        .i_opcode_sbb_imm_to_reg_mem                (w_opcode_sbb_imm_to_reg_mem),
        .i_opcode_sbb_reg_mem_to_reg                (w_opcode_sbb_reg_mem_to_reg),
        .i_opcode_sbb_reg_to_reg_mem                (w_opcode_sbb_reg_to_reg_mem),
        .i_opcode_scas                              (w_opcode_scas),
        .i_opcode_setcc                             (w_opcode_setcc),
        .i_opcode_sgdt                              (w_opcode_sgdt),
        .i_opcode_shl_1                             (w_opcode_shl_1),
        .i_opcode_shl_cl                            (w_opcode_shl_cl),
        .i_opcode_shl_imm                           (w_opcode_shl_imm),
        .i_opcode_shld_cl                           (w_opcode_shld_cl),
        .i_opcode_shld_imm                          (w_opcode_shld_imm),
        .i_opcode_shr_1                             (w_opcode_shr_1),
        .i_opcode_shr_cl                            (w_opcode_shr_cl),
        .i_opcode_shr_imm                           (w_opcode_shr_imm),
        .i_opcode_shrd_cl                           (w_opcode_shrd_cl),
        .i_opcode_shrd_imm                          (w_opcode_shrd_imm),
        .i_opcode_sidt                              (w_opcode_sidt),
        .i_opcode_sldt                              (w_opcode_sldt),
        .i_opcode_smsw                              (w_opcode_smsw),
        .i_opcode_stc                               (w_opcode_stc),
        .i_opcode_std                               (w_opcode_std),
        .i_opcode_sti                               (w_opcode_sti),
        .i_opcode_stos                              (w_opcode_stos),
        .i_opcode_str                               (w_opcode_str),
        .i_opcode_sub_imm_to_acc                    (w_opcode_sub_imm_to_acc),
        .i_opcode_sub_imm_to_reg_mem                (w_opcode_sub_imm_to_reg_mem),
        .i_opcode_sub_reg_mem_to_reg                (w_opcode_sub_reg_mem_to_reg),
        .i_opcode_sub_reg_to_reg_mem                (w_opcode_sub_reg_to_reg_mem),
        .i_opcode_test_imm_acc                      (w_opcode_test_imm_acc),
        .i_opcode_test_imm_reg_mem                  (w_opcode_test_imm_reg_mem),
        .i_opcode_test_reg_mem                      (w_opcode_test_reg_mem),
        .i_opcode_ud0                               (w_opcode_ud0),
        .i_opcode_ud1                               (w_opcode_ud1),
        .i_opcode_ud2                               (w_opcode_ud2),
        .i_opcode_verr                              (w_opcode_verr),
        .i_opcode_verw                              (w_opcode_verw),
        .i_opcode_wait                              (w_opcode_wait),
        .i_opcode_wbinvd                            (w_opcode_wbinvd),
        .i_opcode_wrmsr                             (w_opcode_wrmsr),
        .i_opcode_x87_esc                           (w_opcode_x87_esc),
        .i_opcode_mmx_any                           (w_opcode_mmx_any),
        .i_opcode_mmx_emms                          (w_opcode_mmx_emms),
        .i_opcode_sse_any                           (w_opcode_sse_any),
        .i_opcode_xadd                              (w_opcode_xadd),
        .i_opcode_xchg_acc                          (w_opcode_xchg_acc),
        .i_opcode_xchg_reg_mem                      (w_opcode_xchg_reg_mem),
        .i_opcode_xlat                              (w_opcode_xlat),
        .i_opcode_xor_imm_to_acc                    (w_opcode_xor_imm_to_acc),
        .i_opcode_xor_imm_to_reg_mem                (w_opcode_xor_imm_to_reg_mem),
        .i_opcode_xor_reg_mem_to_reg                (w_opcode_xor_reg_mem_to_reg),
        .i_opcode_xor_reg_to_reg_mem                (w_opcode_xor_reg_to_reg_mem),
        .i_tttn                                     (w_tttn),
        .i_stage2_valid           (uop_stage2_valid),
        .i_flush                  (i_uop_flush),
        .o_stage2_ready           (uop_stage2_ready),
        .o_stage_valid            (o_uop_valid),
        .o_uop                    (o_uop),
        .i_stage4_ready           (i_reg_ready),
        .clk                      (clk),
        .rst_n                    (rst_n)
    );

endmodule
