# Experimental baseline currently mirrors rtl_fullcore.f.
+incdir+rtl
+incdir+rtl/cpu
+incdir+@include
rtl/bus_controller.sv
rtl/openx86_soc_top.sv
rtl/chipset/chip_8237_dma.sv
rtl/chipset/chip_8254_pit.sv
rtl/chipset/chip_8259_pic.sv
rtl/chipset/chip_at24lc32_eeprom.sv
rtl/device/ide_controller.sv
rtl/chipset/chip_centronics_lpt.sv
rtl/chipset/chip_i8042_ps2.sv
rtl/chipset/chip_mc146818_rtc.sv
rtl/chipset/chip_ns16550_com.sv
rtl/chipset/chip_pc_bios_eeprom.sv
rtl/common/dual_port_rom.sv
rtl/common/edge_detect.sv
rtl/common/simple_dual_port_ram.sv
rtl/common/single_port_ram.sv
rtl/common/single_port_rom.sv
rtl/common/true_dual_port_ram.sv
rtl/cpu/stage_1_2_ifu_dec/stage_1_2_ifu_dec.sv
rtl/cpu/stage_2_3_dec_exe/stage_2_3_dec_exe.sv
rtl/cpu/stage_3_4_exe_mem/stage_3_4_exe_mem.sv
rtl/cpu/stage_4_5_mem_wrb/stage_4_5_mem_wrb.sv
rtl/cpu/w686_core.sv
rtl/cpu/cpu.sv
rtl/cpu/stage_1_ifu/stage_1_ifu.sv
rtl/cpu/stage_1_ifu/stage_1_ifu_instruction_fetch.sv
rtl/cpu/mmu/mmu_memory_management_unit.sv
rtl/cpu/mmu/mmu_pg_paging_unit.sv
rtl/cpu/mmu/mmu_seg_gate_segment_descriptor_decode.sv
rtl/cpu/mmu/mmu_seg_segmentation_unit.sv
rtl/cpu/mmu/mmu_seg_segment_descriptor_cache.sv
rtl/cpu/mmu/mmu_seg_segment_descriptor_decode.sv
rtl/cpu/mmu/mmu_seg_segment_descriptor_encode.sv
rtl/cpu/mmu/mmu_seg_system_segment_descriptor_decode.sv
rtl/cpu/stage_2_dec/stage_2_dec.sv
rtl/cpu/stage_2_dec/stage_2_dec_decode_disp_imm.sv
rtl/cpu/stage_2_dec/stage_2_dec_decode_field.sv
rtl/cpu/stage_2_dec/stage_2_dec_decode_mod_rm.sv
rtl/cpu/stage_2_dec/stage_2_dec_decode_opcode_x86.sv
rtl/cpu/stage_2_dec/stage_2_dec_decode_prefix.sv
rtl/cpu/stage_2_dec/stage_2_dec_decode_prefix_all.sv
rtl/cpu/stage_2_dec/stage_2_dec_decode_sib.sv
rtl/cpu/stage_2_dec/stage_2_dec_decode_unit.sv
rtl/cpu/stage_2_dec/stage_2_dec_decode_x87_esc.sv
rtl/cpu/stage_3_exe/ctrl/stage_3_exe.sv
rtl/cpu/stage_3_exe/agu_lsu/stage_3_exe_address_generation_unit.sv
rtl/cpu/stage_3_exe/alu/arithmetic/stage_3_exe_ari_adc.sv
rtl/cpu/stage_3_exe/alu/arithmetic/stage_3_exe_ari_add.sv
rtl/cpu/stage_3_exe/alu/arithmetic/stage_3_exe_ari_dec.sv
rtl/cpu/stage_3_exe/alu/arithmetic/stage_3_exe_ari_execute_arithmetic_adc.sv
rtl/cpu/stage_3_exe/alu/arithmetic/stage_3_exe_ari_execute_arithmetic_add.sv
rtl/cpu/stage_3_exe/alu/arithmetic/stage_3_exe_ari_execute_arithmetic_div.sv
rtl/cpu/stage_3_exe/alu/arithmetic/stage_3_exe_ari_execute_arithmetic_mul.sv
rtl/cpu/stage_3_exe/alu/arithmetic/stage_3_exe_ari_execute_arithmetic_sbb.sv
rtl/cpu/stage_3_exe/alu/arithmetic/stage_3_exe_ari_execute_arithmetic_sub.sv
rtl/cpu/stage_3_exe/alu/arithmetic/stage_3_exe_ari_inc.sv
rtl/cpu/stage_3_exe/alu/arithmetic/stage_3_exe_ari_neg.sv
rtl/cpu/stage_3_exe/alu/arithmetic/stage_3_exe_ari_sbb.sv
rtl/cpu/stage_3_exe/alu/arithmetic/stage_3_exe_ari_sub.sv
rtl/cpu/stage_3_exe/alu/bitmanip/stage_3_exe_bit_bsf.sv
rtl/cpu/stage_3_exe/alu/bitmanip/stage_3_exe_bit_bsr.sv
rtl/cpu/stage_3_exe/alu/bitmanip/stage_3_exe_bit_bt.sv
rtl/cpu/stage_3_exe/alu/bitmanip/stage_3_exe_bit_btc.sv
rtl/cpu/stage_3_exe/alu/bitmanip/stage_3_exe_bit_btr.sv
rtl/cpu/stage_3_exe/alu/bitmanip/stage_3_exe_bit_bts.sv
rtl/cpu/stage_3_exe/branch/stage_3_exe_execute_branch_unit.sv
rtl/cpu/stage_3_exe/muldiv/stage_3_exe_execute_muldiv_unit.sv
rtl/cpu/stage_3_exe/ctrl/stage_3_exe_execute_unit.sv
rtl/cpu/stage_3_exe/fpu/stage_3_exe_execute_x87_fpu.sv
rtl/cpu/stage_3_exe/agu_lsu/stage_3_exe_ld_execute_load_segment.sv
rtl/cpu/stage_3_exe/agu_lsu/stage_3_exe_load_store_unit.sv
rtl/cpu/stage_3_exe/alu/logic/stage_3_exe_log_and.sv
rtl/cpu/stage_3_exe/alu/logic/stage_3_exe_log_execute_logic_and.sv
rtl/cpu/stage_3_exe/alu/logic/stage_3_exe_log_execute_logic_not.sv
rtl/cpu/stage_3_exe/alu/logic/stage_3_exe_log_execute_logic_or.sv
rtl/cpu/stage_3_exe/alu/logic/stage_3_exe_log_execute_logic_xor.sv
rtl/cpu/stage_3_exe/alu/logic/stage_3_exe_log_not.sv
rtl/cpu/stage_3_exe/alu/logic/stage_3_exe_log_or.sv
rtl/cpu/stage_3_exe/alu/logic/stage_3_exe_log_xor.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_aaa.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_aad.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_aam.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_aas.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_arpl.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_bswap.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_cbw.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_cdq.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_clts.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_cmpxchg.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_daa.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_das.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_flag_status.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_imul_imm.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_lahf.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_lar.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_lmsw.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_loop_ctrl.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_lsl.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_movsx.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_movzx.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_sahf.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_setcc.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_smsw.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_stridx_step.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_verr.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_xadd.sv
rtl/cpu/stage_3_exe/alu/misc/stage_3_exe_misc_xchg.sv
rtl/cpu/stage_3_exe/alu/shift_rotate/stage_3_exe_rot_execute_rotate_left.sv
rtl/cpu/stage_3_exe/alu/shift_rotate/stage_3_exe_rot_execute_rotate_right.sv
rtl/cpu/stage_3_exe/alu/shift_rotate/stage_3_exe_rot_rcl.sv
rtl/cpu/stage_3_exe/alu/shift_rotate/stage_3_exe_rot_rcr.sv
rtl/cpu/stage_3_exe/alu/shift_rotate/stage_3_exe_rot_rol.sv
rtl/cpu/stage_3_exe/alu/shift_rotate/stage_3_exe_rot_ror.sv
rtl/cpu/stage_3_exe/alu/shift_rotate/stage_3_exe_shf_execute_shift_left.sv
rtl/cpu/stage_3_exe/alu/shift_rotate/stage_3_exe_shf_execute_shift_right.sv
rtl/cpu/stage_3_exe/alu/shift_rotate/stage_3_exe_shf_sar.sv
rtl/cpu/stage_3_exe/alu/shift_rotate/stage_3_exe_shf_shl.sv
rtl/cpu/stage_3_exe/alu/shift_rotate/stage_3_exe_shf_shld.sv
rtl/cpu/stage_3_exe/alu/shift_rotate/stage_3_exe_shf_shr.sv
rtl/cpu/stage_3_exe/alu/shift_rotate/stage_3_exe_shf_shrd.sv
rtl/cpu/stage_3_exe/ctrl/stage_3_exe_w686_core_execute_i486.sv
rtl/cpu/stage_4_mem/stage_4_mem.sv
rtl/cpu/stage_4_mem/stage_4_mem_access_memory.sv
rtl/cpu/bus_interface_unit.sv
rtl/cpu/stage_5_wrb/stage_5_wrb.sv
rtl/cpu/register_files/rf_control_register.sv
rtl/cpu/register_files/rf_debug_register.sv
rtl/cpu/register_files/rf_flags_register.sv
rtl/cpu/register_files/rf_gdtr_register.sv
rtl/cpu/register_files/rf_general_purpose_register.sv
rtl/cpu/register_files/rf_idtr_register.sv
rtl/cpu/register_files/rf_instruction_pointer_register.sv
rtl/cpu/register_files/rf_segment_register.sv
rtl/cpu/register_files/rf_test_register.sv
rtl/cpu/stage_5_wrb/stage_5_wrb_wb_write_back_unit.sv
rtl/memory/sdram_controller.sv
rtl/device/ps2/ps2_host_phy.sv
rtl/peripheral/sdcard/sdcard_4bit_phy.sv
rtl/peripheral/sdcard/sdcard_native_host_4bit.sv
rtl/peripheral/sdcard/sdcard_controller.sv
rtl/device/vga/vga_font_rom.sv
rtl/device/vga/vga_graphics_adapter.sv
rtl/device/vga/vga_port.sv
rtl/device/vga/vga_text_color.sv
rtl/device/vga/vga_text_intense.sv
