# Experimental baseline currently mirrors rtl_fullcore.f.
+incdir+rtl
+incdir+rtl/cpu
+incdir+rtl/cpu/include
+incdir+@include
rtl/bus_controller.sv
rtl/openx86_soc_top.sv
rtl/chipset/chip_8237_dma.sv
rtl/chipset/chip_8254_pit.sv
rtl/chipset/chip_8259_pic.sv
rtl/chipset/chip_at24lc32_eeprom.sv
rtl/device/ide_controller.sv
rtl/chipset/chip_centronics_lpt.sv
rtl/chipset/chip_i8042_ps2.sv
rtl/chipset/chip_mc146818_rtc.sv
rtl/chipset/chip_ns16550_com.sv
rtl/chipset/chip_pc_bios_eeprom.sv
rtl/common/dual_port_rom.sv
rtl/common/edge_detect.sv
rtl/common/simple_dual_port_ram.sv
rtl/common/single_port_ram.sv
rtl/common/single_port_rom.sv
rtl/common/true_dual_port_ram.sv
rtl/cpu/biu/bus_interface_unit.sv
rtl/cpu/eu/agu_lsu/address_generation_unit.sv
rtl/cpu/eu/agu_lsu/ld_execute_load_segment.sv
rtl/cpu/eu/agu_lsu/load_store_unit.sv
rtl/cpu/eu/alu/arithmetic/ari_adc.sv
rtl/cpu/eu/alu/arithmetic/ari_add.sv
rtl/cpu/eu/alu/arithmetic/ari_dec.sv
rtl/cpu/eu/alu/arithmetic/ari_execute_arithmetic_adc.sv
rtl/cpu/eu/alu/arithmetic/ari_execute_arithmetic_add.sv
rtl/cpu/eu/alu/arithmetic/ari_execute_arithmetic_div.sv
rtl/cpu/eu/alu/arithmetic/ari_execute_arithmetic_mul.sv
rtl/cpu/eu/alu/arithmetic/ari_execute_arithmetic_sbb.sv
rtl/cpu/eu/alu/arithmetic/ari_execute_arithmetic_sub.sv
rtl/cpu/eu/alu/arithmetic/ari_inc.sv
rtl/cpu/eu/alu/arithmetic/ari_neg.sv
rtl/cpu/eu/alu/arithmetic/ari_sbb.sv
rtl/cpu/eu/alu/arithmetic/ari_sub.sv
rtl/cpu/eu/alu/bitmanip/bit_bsf.sv
rtl/cpu/eu/alu/bitmanip/bit_bsr.sv
rtl/cpu/eu/alu/bitmanip/bit_bt.sv
rtl/cpu/eu/alu/bitmanip/bit_btc.sv
rtl/cpu/eu/alu/bitmanip/bit_btr.sv
rtl/cpu/eu/alu/bitmanip/bit_bts.sv
rtl/cpu/eu/alu/logic/log_and.sv
rtl/cpu/eu/alu/logic/log_execute_logic_and.sv
rtl/cpu/eu/alu/logic/log_execute_logic_not.sv
rtl/cpu/eu/alu/logic/log_execute_logic_or.sv
rtl/cpu/eu/alu/logic/log_execute_logic_xor.sv
rtl/cpu/eu/alu/logic/log_not.sv
rtl/cpu/eu/alu/logic/log_or.sv
rtl/cpu/eu/alu/logic/log_xor.sv
rtl/cpu/eu/alu/misc/misc_aaa.sv
rtl/cpu/eu/alu/misc/misc_aad.sv
rtl/cpu/eu/alu/misc/misc_aam.sv
rtl/cpu/eu/alu/misc/misc_aas.sv
rtl/cpu/eu/alu/misc/misc_arpl.sv
rtl/cpu/eu/alu/misc/misc_bswap.sv
rtl/cpu/eu/alu/misc/misc_cbw.sv
rtl/cpu/eu/alu/misc/misc_cdq.sv
rtl/cpu/eu/alu/misc/misc_clts.sv
rtl/cpu/eu/alu/misc/misc_cmpxchg.sv
rtl/cpu/eu/alu/misc/misc_daa.sv
rtl/cpu/eu/alu/misc/misc_das.sv
rtl/cpu/eu/alu/misc/misc_flag_status.sv
rtl/cpu/eu/alu/misc/misc_imul_imm.sv
rtl/cpu/eu/alu/misc/misc_lahf.sv
rtl/cpu/eu/alu/misc/misc_lar.sv
rtl/cpu/eu/alu/misc/misc_lmsw.sv
rtl/cpu/eu/alu/misc/misc_loop_ctrl.sv
rtl/cpu/eu/alu/misc/misc_lsl.sv
rtl/cpu/eu/alu/misc/misc_movsx.sv
rtl/cpu/eu/alu/misc/misc_movzx.sv
rtl/cpu/eu/alu/misc/misc_sahf.sv
rtl/cpu/eu/alu/misc/misc_setcc.sv
rtl/cpu/eu/alu/misc/misc_smsw.sv
rtl/cpu/eu/alu/misc/misc_stridx_step.sv
rtl/cpu/eu/alu/misc/misc_verr.sv
rtl/cpu/eu/alu/misc/misc_xadd.sv
rtl/cpu/eu/alu/misc/misc_xchg.sv
rtl/cpu/eu/alu/shift_rotate/rot_execute_rotate_left.sv
rtl/cpu/eu/alu/shift_rotate/rot_execute_rotate_right.sv
rtl/cpu/eu/alu/shift_rotate/rot_rcl.sv
rtl/cpu/eu/alu/shift_rotate/rot_rcr.sv
rtl/cpu/eu/alu/shift_rotate/rot_rol.sv
rtl/cpu/eu/alu/shift_rotate/rot_ror.sv
rtl/cpu/eu/alu/shift_rotate/shf_execute_shift_left.sv
rtl/cpu/eu/alu/shift_rotate/shf_execute_shift_right.sv
rtl/cpu/eu/alu/shift_rotate/shf_sar.sv
rtl/cpu/eu/alu/shift_rotate/shf_shl.sv
rtl/cpu/eu/alu/shift_rotate/shf_shld.sv
rtl/cpu/eu/alu/shift_rotate/shf_shr.sv
rtl/cpu/eu/alu/shift_rotate/shf_shrd.sv
rtl/cpu/eu/branch/execute_branch_unit.sv
rtl/cpu/eu/control/execute_stall.sv
rtl/cpu/eu/execute_unit.sv
rtl/cpu/eu/extensions_i486/cache_invalidate.sv
rtl/cpu/eu/extensions_i486/cpuid.sv
rtl/cpu/eu/extensions_i486/execute_unit.sv
rtl/cpu/eu/fpu/execute_x87_fpu.sv
rtl/cpu/eu/muldiv/execute_muldiv_unit.sv
rtl/cpu/iu/decode/decode_stage.sv
rtl/cpu/iu/decode/disp_imm.sv
rtl/cpu/iu/decode/field.sv
rtl/cpu/iu/decode/mod_rm.sv
rtl/cpu/iu/decode/opcode_x86.sv
rtl/cpu/iu/decode/prefix.sv
rtl/cpu/iu/decode/prefix_all.sv
rtl/cpu/iu/decode/sib.sv
rtl/cpu/iu/decode/unit.sv
rtl/cpu/iu/decode/x87_esc.sv
rtl/cpu/iu/prefetch/instruction_fetch.sv
rtl/cpu/iu/prefetch/prefetch_unit.sv
rtl/cpu/mem/access_memory.sv
rtl/cpu/mem/memory_stage.sv
rtl/cpu/mmu/memory_management_unit.sv
rtl/cpu/mmu/paging/paging_unit.sv
rtl/cpu/mmu/segmentation/gate_segment_descriptor_decode.sv
rtl/cpu/mmu/segmentation/segment_descriptor_cache.sv
rtl/cpu/mmu/segmentation/segment_descriptor_decode.sv
rtl/cpu/mmu/segmentation/segment_descriptor_encode.sv
rtl/cpu/mmu/segmentation/segmentation_unit.sv
rtl/cpu/mmu/segmentation/system_segment_descriptor_decode.sv
rtl/cpu/pipe/dec_to_exe/pipeline_boundary.sv
rtl/cpu/pipe/exe_to_mem/pipeline_boundary.sv
rtl/cpu/pipe/if_to_dec/pipeline_boundary.sv
rtl/cpu/pipe/mem_to_wb/pipeline_boundary.sv
rtl/cpu/register_file/rf_control_register.sv
rtl/cpu/register_file/rf_debug_register.sv
rtl/cpu/register_file/rf_flags_register.sv
rtl/cpu/register_file/rf_gdtr_register.sv
rtl/cpu/register_file/rf_general_purpose_register.sv
rtl/cpu/register_file/rf_idtr_register.sv
rtl/cpu/register_file/rf_instruction_pointer_register.sv
rtl/cpu/register_file/rf_segment_register.sv
rtl/cpu/register_file/rf_test_register.sv
rtl/cpu/top/i486_cpu_core.sv
rtl/cpu/top/i486_cpu.sv
rtl/cpu/wb/write_back_stage.sv
rtl/cpu/wb/write_back_unit.sv
rtl/memory/sdram_controller.sv
rtl/device/ps2/ps2_host_phy.sv
rtl/peripheral/sdcard/sdcard_4bit_phy.sv
rtl/peripheral/sdcard/sdcard_native_host_4bit.sv
rtl/peripheral/sdcard/sdcard_controller.sv
rtl/device/vga/vga_font_rom.sv
rtl/device/vga/vga_graphics_adapter.sv
rtl/device/vga/vga_port.sv
rtl/device/vga/vga_text_color.sv
rtl/device/vga/vga_text_intense.sv
