`ifndef OPENX86_DEFINITION_H_SV
`define OPENX86_DEFINITION_H_SV

`define BIT_WIDTH 32
// segment
`define GRANULARITY_BYTE 0
`define GRANULARITY_4K 1
`define DESCRIPTOR_TYPE_SYSTEM 0
`define DESCRIPTOR_TYPE_CODE_OR_DATA 1


`endif
