// ============================================================================
//  Copyright (c) 2026 Chang Wei
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
//
// ----------------------------------------------------------------------------
//  File        : stage_3_uop.sv
//  Author      : Chang Wei <changwei1006@gmail.com>
//  Description : stage_3_uop module
// ============================================================================

`include "openx86_defs.h.sv"

module stage_3_uop (
    // =========================
    // Decoded macro-instruction inputs from stage_2_dec
    // =========================
    input  logic                i_opcode_aaa,
    input  logic                i_opcode_aad,
    input  logic                i_opcode_aam,
    input  logic                i_opcode_aas,
    input  logic                i_opcode_adc_reg_to_reg_mem,
    input  logic                i_opcode_adc_reg_mem_to_reg,
    input  logic                i_opcode_adc_imm_to_reg_mem,
    input  logic                i_opcode_adc_imm_to_acc,
    input  logic                i_opcode_add_reg_to_reg_mem,
    input  logic                i_opcode_add_reg_mem_to_reg,
    input  logic                i_opcode_add_imm_to_reg_mem,
    input  logic                i_opcode_add_imm_to_acc,
    input  logic                i_opcode_and_reg_to_reg_mem,
    input  logic                i_opcode_and_reg_mem_to_reg,
    input  logic                i_opcode_and_imm_to_reg_mem,
    input  logic                i_opcode_and_imm_to_acc,
    input  logic                i_opcode_arpl,
    input  logic                i_opcode_bound,
    input  logic                i_opcode_bsf,
    input  logic                i_opcode_bsr,
    input  logic                i_opcode_bswap,
    input  logic                i_opcode_bt_imm,
    input  logic                i_opcode_bt_reg,
    input  logic                i_opcode_btc_imm,
    input  logic                i_opcode_btc_reg,
    input  logic                i_opcode_btr_imm,
    input  logic                i_opcode_btr_reg,
    input  logic                i_opcode_bts_imm,
    input  logic                i_opcode_bts_reg,
    input  logic                i_opcode_call_near_direct,
    input  logic                i_opcode_call_near_indirect,
    input  logic                i_opcode_call_far_direct,
    input  logic                i_opcode_call_far_indirect,
    input  logic                i_opcode_cbw,
    input  logic                i_opcode_cdq,
    input  logic                i_opcode_clc,
    input  logic                i_opcode_cld,
    input  logic                i_opcode_cli,
    input  logic                i_opcode_clts,
    input  logic                i_opcode_cmc,
    input  logic                i_opcode_cmp_mem_reg,
    input  logic                i_opcode_cmp_reg_mem,
    input  logic                i_opcode_cmp_imm_reg_mem,
    input  logic                i_opcode_cmp_imm_acc,
    input  logic                i_opcode_cmps,
    input  logic                i_opcode_cmpxchg,
    input  logic                i_opcode_cpuid,
    input  logic                i_opcode_cwd,
    input  logic                i_opcode_cwde,
    input  logic                i_opcode_daa,
    input  logic                i_opcode_das,
    input  logic                i_opcode_dec_reg_mem,
    input  logic                i_opcode_dec_reg,
    input  logic                i_opcode_div,
    input  logic                i_opcode_hlt,
    input  logic                i_opcode_idiv,
    input  logic                i_opcode_imul_acc,
    input  logic                i_opcode_imul_reg,
    input  logic                i_opcode_imul_imm,
    input  logic                i_opcode_in_fixed,
    input  logic                i_opcode_in_var,
    input  logic                i_opcode_inc_reg_mem,
    input  logic                i_opcode_inc_reg,
    input  logic                i_opcode_ins,
    input  logic                i_opcode_int_n,
    input  logic                i_opcode_int_3,
    input  logic                i_opcode_int_4,
    input  logic                i_opcode_invd,
    input  logic                i_opcode_invlpg,
    input  logic                i_opcode_invpcid,
    input  logic                i_opcode_iret,
    input  logic                i_opcode_jcc_short,
    input  logic                i_opcode_jcc_near,
    input  logic                i_opcode_jcxz,
    input  logic                i_opcode_jmp_short,
    input  logic                i_opcode_jmp_near_direct,
    input  logic                i_opcode_jmp_near_indirect,
    input  logic                i_opcode_jmp_far_direct,
    input  logic                i_opcode_jmp_far_indirect,
    input  logic                i_opcode_lahf,
    input  logic                i_opcode_lar,
    input  logic                i_opcode_lds,
    input  logic                i_opcode_lea,
    input  logic                i_opcode_leave,
    input  logic                i_opcode_les,
    input  logic                i_opcode_lfs,
    input  logic                i_opcode_lgdt,
    input  logic                i_opcode_lgs,
    input  logic                i_opcode_lidt,
    input  logic                i_opcode_lldt,
    input  logic                i_opcode_lmsw,
    input  logic                i_opcode_lods,
    input  logic                i_opcode_loop,
    input  logic                i_opcode_loopz,
    input  logic                i_opcode_loopnz,
    input  logic                i_opcode_lsl,
    input  logic                i_opcode_lss,
    input  logic                i_opcode_ltr,
    input  logic                i_opcode_mov_reg_to_reg_mem,
    input  logic                i_opcode_mov_reg_mem_to_reg,
    input  logic                i_opcode_mov_imm_to_reg_mem,
    input  logic                i_opcode_mov_imm_to_reg,
    input  logic                i_opcode_mov_mem_to_acc,
    input  logic                i_opcode_mov_acc_to_mem,
    input  logic                i_opcode_mov_cr_from_reg,
    input  logic                i_opcode_mov_reg_from_cr,
    input  logic                i_opcode_mov_dr_from_reg,
    input  logic                i_opcode_mov_reg_from_dr,
    input  logic                i_opcode_mov_tr_from_reg,
    input  logic                i_opcode_mov_reg_from_tr,
    input  logic                i_opcode_mov_reg_mem_to_sreg,
    input  logic                i_opcode_mov_sreg_to_reg_mem,
    input  logic                i_opcode_movbe_mem_reg,
    input  logic                i_opcode_movbe_reg_mem,
    input  logic                i_opcode_movs,
    input  logic                i_opcode_movsx,
    input  logic                i_opcode_movzx,
    input  logic                i_opcode_mul,
    input  logic                i_opcode_neg,
    input  logic                i_opcode_nop,
    input  logic                i_opcode_nop_multibyte,
    input  logic                i_opcode_not,
    input  logic                i_opcode_or_reg_to_reg_mem,
    input  logic                i_opcode_or_reg_mem_to_reg,
    input  logic                i_opcode_or_imm_to_reg_mem,
    input  logic                i_opcode_or_imm_to_acc,
    input  logic                i_opcode_out_fixed,
    input  logic                i_opcode_out_var,
    input  logic                i_opcode_outs,
    input  logic                i_opcode_pop_reg_mem,
    input  logic                i_opcode_pop_reg,
    input  logic                i_opcode_pop_sreg_2,
    input  logic                i_opcode_pop_sreg_3,
    input  logic                i_opcode_popa,
    input  logic                i_opcode_popf,
    input  logic                i_opcode_push_reg_mem,
    input  logic                i_opcode_push_reg,
    input  logic                i_opcode_push_sreg_2,
    input  logic                i_opcode_push_sreg_3,
    input  logic                i_opcode_push_imm,
    input  logic                i_opcode_pusha,
    input  logic                i_opcode_pushf,
    input  logic                i_opcode_rcl_1,
    input  logic                i_opcode_rcl_cl,
    input  logic                i_opcode_rcl_imm,
    input  logic                i_opcode_rcr_1,
    input  logic                i_opcode_rcr_cl,
    input  logic                i_opcode_rcr_imm,
    input  logic                i_opcode_rdmsr,
    input  logic                i_opcode_rdpmc,
    input  logic                i_opcode_rdtsc,
    input  logic                i_opcode_rdtscp,
    input  logic                i_opcode_ret_near,
    input  logic                i_opcode_ret_near_imm,
    input  logic                i_opcode_ret_far,
    input  logic                i_opcode_ret_far_imm,
    input  logic                i_opcode_rol_1,
    input  logic                i_opcode_rol_cl,
    input  logic                i_opcode_rol_imm,
    input  logic                i_opcode_ror_1,
    input  logic                i_opcode_ror_cl,
    input  logic                i_opcode_ror_imm,
    input  logic                i_opcode_rsm,
    input  logic                i_opcode_sahf,
    input  logic                i_opcode_sar_1,
    input  logic                i_opcode_sar_cl,
    input  logic                i_opcode_sar_imm,
    input  logic                i_opcode_sbb_reg_to_reg_mem,
    input  logic                i_opcode_sbb_reg_mem_to_reg,
    input  logic                i_opcode_sbb_imm_to_reg_mem,
    input  logic                i_opcode_sbb_imm_to_acc,
    input  logic                i_opcode_scas,
    input  logic                i_opcode_setcc,
    input  logic                i_opcode_sgdt,
    input  logic                i_opcode_shl_1,
    input  logic                i_opcode_shl_cl,
    input  logic                i_opcode_shl_imm,
    input  logic                i_opcode_shld_imm,
    input  logic                i_opcode_shld_cl,
    input  logic                i_opcode_shr_1,
    input  logic                i_opcode_shr_cl,
    input  logic                i_opcode_shr_imm,
    input  logic                i_opcode_shrd_imm,
    input  logic                i_opcode_shrd_cl,
    input  logic                i_opcode_sidt,
    input  logic                i_opcode_sldt,
    input  logic                i_opcode_smsw,
    input  logic                i_opcode_stc,
    input  logic                i_opcode_std,
    input  logic                i_opcode_sti,
    input  logic                i_opcode_stos,
    input  logic                i_opcode_str,
    input  logic                i_opcode_sub_reg_to_reg_mem,
    input  logic                i_opcode_sub_reg_mem_to_reg,
    input  logic                i_opcode_sub_imm_to_reg_mem,
    input  logic                i_opcode_sub_imm_to_acc,
    input  logic                i_opcode_test_reg_mem,
    input  logic                i_opcode_test_imm_reg_mem,
    input  logic                i_opcode_test_imm_acc,
    input  logic                i_opcode_ud0,
    input  logic                i_opcode_ud1,
    input  logic                i_opcode_ud2,
    input  logic                i_opcode_verr,
    input  logic                i_opcode_verw,
    input  logic                i_opcode_wait,
    input  logic                i_opcode_wbinvd,
    input  logic                i_opcode_wrmsr,
    input  logic                i_opcode_xadd,
    input  logic                i_opcode_xchg_reg_mem,
    input  logic                i_opcode_xchg_acc,
    input  logic                i_opcode_xlat,
    input  logic                i_opcode_xor_reg_to_reg_mem,
    input  logic                i_opcode_xor_reg_mem_to_reg,
    input  logic                i_opcode_xor_imm_to_reg_mem,
    input  logic                i_opcode_xor_imm_to_acc,
    input  logic                i_opcode_x87_esc,
    input  logic [ 4: 0]        i_x87_exe_subop,
    input  logic [ 2: 0]        i_x87_sti,
    input  logic                i_x87_mem_access,
    input  logic                i_x87_is_store,
    input  logic                i_opcode_mmx_any,
    input  logic                i_opcode_mmx_emms,
    input  logic                i_opcode_sse_any,
    input  logic [ 3: 0]        i_tttn,
    input  logic [ 2: 0]        i_eee,

    input  logic [31: 0]        i_dec_displacement,
    input  logic [31: 0]        i_dec_immediate,
    input  logic                i_dec_base_reg_is_present,
    input  logic [ 2: 0]        i_dec_base_reg_index,
    input  logic                i_dec_index_reg_is_present,
    input  logic [ 2: 0]        i_dec_index_reg_index,
    input  logic [ 2: 0]        i_dec_segment_reg_index,
    input  logic [ 1: 0]        i_dec_sib_scale_factor,
    input  logic [ 1: 0]        i_dec_modrm_mod,

    // =========================
    // stage handshake/control
    // =========================
    input  logic                i_stage2_valid,
    input  logic                i_flush,
    output logic                o_stage2_ready,
    output logic                o_stage_valid,

    // =========================
    // Micro-op outputs to stage_4_reg_read
    // =========================
    output micro_op_t           o_uop,

    input  logic                i_stage4_ready,

    input  logic                clk,
    input  logic                rst_n
);

    // ============================================================
    // UOP Queue (FIFO)
    // ============================================================
    localparam int LP_UOP_WIDTH   = 93; // micro_op_t width (84 + tttn:4 + eee:3 + sib_scale:2)
    localparam int LP_QUEUE_DEPTH = 8;

    logic [LP_UOP_WIDTH - 1: 0] uop_data_vector;
    logic [LP_QUEUE_DEPTH - 1: 0][LP_UOP_WIDTH - 1: 0] uop_queue_data;
    logic [LP_UOP_WIDTH - 1: 0] uop_queue_out;
    logic                        queue_push_valid;
    logic                        queue_push_ready;
    logic                        queue_pop_valid;
    logic                        queue_pop_ready;
    logic                        queue_full;
    logic                        queue_empty;
    logic [$clog2(LP_QUEUE_DEPTH + 1) - 1: 0] queue_count;

    // ============================================================
    // Internal signals
    // ============================================================
    micro_op_t           uop_from_dec;
    micro_op_t           uop_from_queue;
    logic                queue_valid;
    logic                pipe_stage3_ready;

    // ============================================================
    // Convert micro_op_t to vector for FIFO
    // ============================================================
    assign uop_data_vector = uop_from_dec;

    // ============================================================
    // dec_to_uop module
    // ============================================================
    dec_to_uop u_dec_to_uop (
        // Decoded macro-instruction inputs
        .i_opcode_aaa                 ( i_opcode_aaa ),
        .i_opcode_aad                 ( i_opcode_aad ),
        .i_opcode_aam                 ( i_opcode_aam ),
        .i_opcode_aas                 ( i_opcode_aas ),
        .i_opcode_adc_reg_to_reg_mem  ( i_opcode_adc_reg_to_reg_mem ),
        .i_opcode_adc_reg_mem_to_reg  ( i_opcode_adc_reg_mem_to_reg ),
        .i_opcode_adc_imm_to_reg_mem  ( i_opcode_adc_imm_to_reg_mem ),
        .i_opcode_adc_imm_to_acc      ( i_opcode_adc_imm_to_acc ),
        .i_opcode_add_reg_to_reg_mem  ( i_opcode_add_reg_to_reg_mem ),
        .i_opcode_add_reg_mem_to_reg  ( i_opcode_add_reg_mem_to_reg ),
        .i_opcode_add_imm_to_reg_mem  ( i_opcode_add_imm_to_reg_mem ),
        .i_opcode_add_imm_to_acc      ( i_opcode_add_imm_to_acc ),
        .i_opcode_and_reg_to_reg_mem  ( i_opcode_and_reg_to_reg_mem ),
        .i_opcode_and_reg_mem_to_reg  ( i_opcode_and_reg_mem_to_reg ),
        .i_opcode_and_imm_to_reg_mem  ( i_opcode_and_imm_to_reg_mem ),
        .i_opcode_and_imm_to_acc      ( i_opcode_and_imm_to_acc ),
        .i_opcode_arpl                ( i_opcode_arpl ),
        .i_opcode_bound              ( i_opcode_bound ),
        .i_opcode_bsf                ( i_opcode_bsf ),
        .i_opcode_bsr                ( i_opcode_bsr ),
        .i_opcode_bswap              ( i_opcode_bswap ),
        .i_opcode_bt_imm             ( i_opcode_bt_imm ),
        .i_opcode_bt_reg             ( i_opcode_bt_reg ),
        .i_opcode_btc_imm            ( i_opcode_btc_imm ),
        .i_opcode_btc_reg            ( i_opcode_btc_reg ),
        .i_opcode_btr_imm            ( i_opcode_btr_imm ),
        .i_opcode_btr_reg            ( i_opcode_btr_reg ),
        .i_opcode_bts_imm            ( i_opcode_bts_imm ),
        .i_opcode_bts_reg            ( i_opcode_bts_reg ),
        .i_opcode_call_near_direct   ( i_opcode_call_near_direct ),
        .i_opcode_call_near_indirect ( i_opcode_call_near_indirect ),
        .i_opcode_call_far_direct    ( i_opcode_call_far_direct ),
        .i_opcode_call_far_indirect  ( i_opcode_call_far_indirect ),
        .i_opcode_cbw                ( i_opcode_cbw ),
        .i_opcode_cdq                ( i_opcode_cdq ),
        .i_opcode_clc                ( i_opcode_clc ),
        .i_opcode_cld                ( i_opcode_cld ),
        .i_opcode_cli                ( i_opcode_cli ),
        .i_opcode_clts               ( i_opcode_clts ),
        .i_opcode_cmc                ( i_opcode_cmc ),
        .i_opcode_cmp_mem_reg        ( i_opcode_cmp_mem_reg ),
        .i_opcode_cmp_reg_mem        ( i_opcode_cmp_reg_mem ),
        .i_opcode_cmp_imm_reg_mem    ( i_opcode_cmp_imm_reg_mem ),
        .i_opcode_cmp_imm_acc        ( i_opcode_cmp_imm_acc ),
        .i_opcode_cmps               ( i_opcode_cmps ),
        .i_opcode_cmpxchg            ( i_opcode_cmpxchg ),
        .i_opcode_cpuid              ( i_opcode_cpuid ),
        .i_opcode_cwd                ( i_opcode_cwd ),
        .i_opcode_cwde               ( i_opcode_cwde ),
        .i_opcode_daa                ( i_opcode_daa ),
        .i_opcode_das                ( i_opcode_das ),
        .i_opcode_dec_reg_mem        ( i_opcode_dec_reg_mem ),
        .i_opcode_dec_reg           ( i_opcode_dec_reg ),
        .i_opcode_div                ( i_opcode_div ),
        .i_opcode_hlt                ( i_opcode_hlt ),
        .i_opcode_idiv               ( i_opcode_idiv ),
        .i_opcode_imul_acc           ( i_opcode_imul_acc ),
        .i_opcode_imul_reg           ( i_opcode_imul_reg ),
        .i_opcode_imul_imm           ( i_opcode_imul_imm ),
        .i_opcode_in_fixed           ( i_opcode_in_fixed ),
        .i_opcode_in_var             ( i_opcode_in_var ),
        .i_opcode_inc_reg_mem        ( i_opcode_inc_reg_mem ),
        .i_opcode_inc_reg            ( i_opcode_inc_reg ),
        .i_opcode_ins                ( i_opcode_ins ),
        .i_opcode_int_n              ( i_opcode_int_n ),
        .i_opcode_int_3              ( i_opcode_int_3 ),
        .i_opcode_int_4              ( i_opcode_int_4 ),
        .i_opcode_invd               ( i_opcode_invd ),
        .i_opcode_invlpg             ( i_opcode_invlpg ),
        .i_opcode_invpcid            ( i_opcode_invpcid ),
        .i_opcode_iret               ( i_opcode_iret ),
        .i_opcode_jcc_short          ( i_opcode_jcc_short ),
        .i_opcode_jcc_near           ( i_opcode_jcc_near ),
        .i_opcode_jcxz               ( i_opcode_jcxz ),
        .i_opcode_jmp_short          ( i_opcode_jmp_short ),
        .i_opcode_jmp_near_direct    ( i_opcode_jmp_near_direct ),
        .i_opcode_jmp_near_indirect  ( i_opcode_jmp_near_indirect ),
        .i_opcode_jmp_far_direct     ( i_opcode_jmp_far_direct ),
        .i_opcode_jmp_far_indirect   ( i_opcode_jmp_far_indirect ),
        .i_opcode_lahf               ( i_opcode_lahf ),
        .i_opcode_lar                ( i_opcode_lar ),
        .i_opcode_lds                ( i_opcode_lds ),
        .i_opcode_lea                ( i_opcode_lea ),
        .i_opcode_leave              ( i_opcode_leave ),
        .i_opcode_les                ( i_opcode_les ),
        .i_opcode_lfs                ( i_opcode_lfs ),
        .i_opcode_lgdt               ( i_opcode_lgdt ),
        .i_opcode_lgs                ( i_opcode_lgs ),
        .i_opcode_lidt               ( i_opcode_lidt ),
        .i_opcode_lldt               ( i_opcode_lldt ),
        .i_opcode_lmsw               ( i_opcode_lmsw ),
        .i_opcode_lods               ( i_opcode_lods ),
        .i_opcode_loop               ( i_opcode_loop ),
        .i_opcode_loopz              ( i_opcode_loopz ),
        .i_opcode_loopnz             ( i_opcode_loopnz ),
        .i_opcode_lsl                ( i_opcode_lsl ),
        .i_opcode_lss                ( i_opcode_lss ),
        .i_opcode_ltr                ( i_opcode_ltr ),
        .i_opcode_mov_reg_to_reg_mem ( i_opcode_mov_reg_to_reg_mem ),
        .i_opcode_mov_reg_mem_to_reg ( i_opcode_mov_reg_mem_to_reg ),
        .i_opcode_mov_imm_to_reg_mem ( i_opcode_mov_imm_to_reg_mem ),
        .i_opcode_mov_imm_to_reg     ( i_opcode_mov_imm_to_reg ),
        .i_opcode_mov_mem_to_acc     ( i_opcode_mov_mem_to_acc ),
        .i_opcode_mov_acc_to_mem     ( i_opcode_mov_acc_to_mem ),
        .i_opcode_mov_cr_from_reg   ( i_opcode_mov_cr_from_reg ),
        .i_opcode_mov_reg_from_cr    ( i_opcode_mov_reg_from_cr ),
        .i_opcode_mov_dr_from_reg    ( i_opcode_mov_dr_from_reg ),
        .i_opcode_mov_reg_from_dr    ( i_opcode_mov_reg_from_dr ),
        .i_opcode_mov_tr_from_reg    ( i_opcode_mov_tr_from_reg ),
        .i_opcode_mov_reg_from_tr    ( i_opcode_mov_reg_from_tr ),
        .i_opcode_mov_reg_mem_to_sreg( i_opcode_mov_reg_mem_to_sreg ),
        .i_opcode_mov_sreg_to_reg_mem( i_opcode_mov_sreg_to_reg_mem ),
        .i_opcode_movbe_mem_reg      ( i_opcode_movbe_mem_reg ),
        .i_opcode_movbe_reg_mem      ( i_opcode_movbe_reg_mem ),
        .i_opcode_movs               ( i_opcode_movs ),
        .i_opcode_movsx              ( i_opcode_movsx ),
        .i_opcode_movzx              ( i_opcode_movzx ),
        .i_opcode_mul                ( i_opcode_mul ),
        .i_opcode_neg                ( i_opcode_neg ),
        .i_opcode_nop                ( i_opcode_nop ),
        .i_opcode_nop_multibyte      ( i_opcode_nop_multibyte ),
        .i_opcode_not                ( i_opcode_not ),
        .i_opcode_or_reg_to_reg_mem  ( i_opcode_or_reg_to_reg_mem ),
        .i_opcode_or_reg_mem_to_reg  ( i_opcode_or_reg_mem_to_reg ),
        .i_opcode_or_imm_to_reg_mem  ( i_opcode_or_imm_to_reg_mem ),
        .i_opcode_or_imm_to_acc      ( i_opcode_or_imm_to_acc ),
        .i_opcode_out_fixed          ( i_opcode_out_fixed ),
        .i_opcode_out_var            ( i_opcode_out_var ),
        .i_opcode_outs               ( i_opcode_outs ),
        .i_opcode_pop_reg_mem        ( i_opcode_pop_reg_mem ),
        .i_opcode_pop_reg            ( i_opcode_pop_reg ),
        .i_opcode_pop_sreg_2         ( i_opcode_pop_sreg_2 ),
        .i_opcode_pop_sreg_3         ( i_opcode_pop_sreg_3 ),
        .i_opcode_popa               ( i_opcode_popa ),
        .i_opcode_popf               ( i_opcode_popf ),
        .i_opcode_push_reg_mem       ( i_opcode_push_reg_mem ),
        .i_opcode_push_reg           ( i_opcode_push_reg ),
        .i_opcode_push_sreg_2        ( i_opcode_push_sreg_2 ),
        .i_opcode_push_sreg_3        ( i_opcode_push_sreg_3 ),
        .i_opcode_push_imm           ( i_opcode_push_imm ),
        .i_opcode_pusha              ( i_opcode_pusha ),
        .i_opcode_pushf              ( i_opcode_pushf ),
        .i_opcode_rcl_1              ( i_opcode_rcl_1 ),
        .i_opcode_rcl_cl             ( i_opcode_rcl_cl ),
        .i_opcode_rcl_imm            ( i_opcode_rcl_imm ),
        .i_opcode_rcr_1              ( i_opcode_rcr_1 ),
        .i_opcode_rcr_cl             ( i_opcode_rcr_cl ),
        .i_opcode_rcr_imm            ( i_opcode_rcr_imm ),
        .i_opcode_rdmsr              ( i_opcode_rdmsr ),
        .i_opcode_rdpmc              ( i_opcode_rdpmc ),
        .i_opcode_rdtsc              ( i_opcode_rdtsc ),
        .i_opcode_rdtscp             ( i_opcode_rdtscp ),
        .i_opcode_ret_near          ( i_opcode_ret_near ),
        .i_opcode_ret_near_imm      ( i_opcode_ret_near_imm ),
        .i_opcode_ret_far            ( i_opcode_ret_far ),
        .i_opcode_ret_far_imm        ( i_opcode_ret_far_imm ),
        .i_opcode_rol_1              ( i_opcode_rol_1 ),
        .i_opcode_rol_cl             ( i_opcode_rol_cl ),
        .i_opcode_rol_imm            ( i_opcode_rol_imm ),
        .i_opcode_ror_1              ( i_opcode_ror_1 ),
        .i_opcode_ror_cl             ( i_opcode_ror_cl ),
        .i_opcode_ror_imm            ( i_opcode_ror_imm ),
        .i_opcode_rsm                ( i_opcode_rsm ),
        .i_opcode_sahf               ( i_opcode_sahf ),
        .i_opcode_sar_1              ( i_opcode_sar_1 ),
        .i_opcode_sar_cl             ( i_opcode_sar_cl ),
        .i_opcode_sar_imm            ( i_opcode_sar_imm ),
        .i_opcode_sbb_reg_to_reg_mem ( i_opcode_sbb_reg_to_reg_mem ),
        .i_opcode_sbb_reg_mem_to_reg ( i_opcode_sbb_reg_mem_to_reg ),
        .i_opcode_sbb_imm_to_reg_mem ( i_opcode_sbb_imm_to_reg_mem ),
        .i_opcode_sbb_imm_to_acc     ( i_opcode_sbb_imm_to_acc ),
        .i_opcode_scas               ( i_opcode_scas ),
        .i_opcode_setcc              ( i_opcode_setcc ),
        .i_opcode_sgdt               ( i_opcode_sgdt ),
        .i_opcode_shl_1              ( i_opcode_shl_1 ),
        .i_opcode_shl_cl             ( i_opcode_shl_cl ),
        .i_opcode_shl_imm            ( i_opcode_shl_imm ),
        .i_opcode_shld_imm           ( i_opcode_shld_imm ),
        .i_opcode_shld_cl            ( i_opcode_shld_cl ),
        .i_opcode_shr_1              ( i_opcode_shr_1 ),
        .i_opcode_shr_cl             ( i_opcode_shr_cl ),
        .i_opcode_shr_imm            ( i_opcode_shr_imm ),
        .i_opcode_shrd_imm           ( i_opcode_shrd_imm ),
        .i_opcode_shrd_cl            ( i_opcode_shrd_cl ),
        .i_opcode_sidt               ( i_opcode_sidt ),
        .i_opcode_sldt               ( i_opcode_sldt ),
        .i_opcode_smsw               ( i_opcode_smsw ),
        .i_opcode_stc                ( i_opcode_stc ),
        .i_opcode_std                ( i_opcode_std ),
        .i_opcode_sti                ( i_opcode_sti ),
        .i_opcode_stos               ( i_opcode_stos ),
        .i_opcode_str                ( i_opcode_str ),
        .i_opcode_sub_reg_to_reg_mem ( i_opcode_sub_reg_to_reg_mem ),
        .i_opcode_sub_reg_mem_to_reg ( i_opcode_sub_reg_mem_to_reg ),
        .i_opcode_sub_imm_to_reg_mem ( i_opcode_sub_imm_to_reg_mem ),
        .i_opcode_sub_imm_to_acc     ( i_opcode_sub_imm_to_acc ),
        .i_opcode_test_reg_mem       ( i_opcode_test_reg_mem ),
        .i_opcode_test_imm_reg_mem   ( i_opcode_test_imm_reg_mem ),
        .i_opcode_test_imm_acc       ( i_opcode_test_imm_acc ),
        .i_opcode_ud0                ( i_opcode_ud0 ),
        .i_opcode_ud1                ( i_opcode_ud1 ),
        .i_opcode_ud2                ( i_opcode_ud2 ),
        .i_opcode_verr               ( i_opcode_verr ),
        .i_opcode_verw               ( i_opcode_verw ),
        .i_opcode_wait               ( i_opcode_wait ),
        .i_opcode_wbinvd             ( i_opcode_wbinvd ),
        .i_opcode_wrmsr              ( i_opcode_wrmsr ),
        .i_opcode_xadd               ( i_opcode_xadd ),
        .i_opcode_xchg_reg_mem       ( i_opcode_xchg_reg_mem ),
        .i_opcode_xchg_acc           ( i_opcode_xchg_acc ),
        .i_opcode_xlat               ( i_opcode_xlat ),
        .i_opcode_xor_reg_to_reg_mem ( i_opcode_xor_reg_to_reg_mem ),
        .i_opcode_xor_reg_mem_to_reg ( i_opcode_xor_reg_mem_to_reg ),
        .i_opcode_xor_imm_to_reg_mem ( i_opcode_xor_imm_to_reg_mem ),
        .i_opcode_xor_imm_to_acc     ( i_opcode_xor_imm_to_acc ),
        .i_opcode_x87_esc            ( i_opcode_x87_esc ),
        .i_x87_exe_subop             ( i_x87_exe_subop ),
        .i_x87_sti                   ( i_x87_sti ),
        .i_x87_mem_access            ( i_x87_mem_access ),
        .i_x87_is_store              ( i_x87_is_store ),
        .i_opcode_mmx_any            ( i_opcode_mmx_any ),
        .i_opcode_mmx_emms           ( i_opcode_mmx_emms ),
        .i_opcode_sse_any            ( i_opcode_sse_any ),
        .i_tttn                      ( i_tttn ),
        .i_eee                       ( i_eee ),

        .i_dec_displacement         ( i_dec_displacement ),
        .i_dec_immediate            ( i_dec_immediate ),
        .i_dec_base_reg_is_present  ( i_dec_base_reg_is_present ),
        .i_dec_base_reg_index       ( i_dec_base_reg_index ),
        .i_dec_index_reg_is_present ( i_dec_index_reg_is_present ),
        .i_dec_index_reg_index      ( i_dec_index_reg_index ),
        .i_dec_segment_reg_index    ( i_dec_segment_reg_index ),
        .i_dec_sib_scale_factor     ( i_dec_sib_scale_factor ),
        .i_dec_modrm_mod            ( i_dec_modrm_mod ),

        // Stage handshake
        .i_stage2_valid             ( i_stage2_valid ),

        // Micro-op output
        .o_uop                      ( uop_from_dec )
    );

    // ============================================================
    // UOP Queue instantiation
    // ============================================================
    fifo #(
        .P_DEPTH      ( LP_QUEUE_DEPTH ),
        .P_DATA_WIDTH ( LP_UOP_WIDTH )
    ) u_uop_queue (
        .i_push_valid ( i_stage2_valid & ~i_flush ),
        .i_push_data  ( uop_queue_data ),
        .i_push_bytes ( 4'd1 ),
        .o_push_ready ( queue_push_ready ),
        .i_pop_valid  ( ~queue_empty & pipe_stage3_ready & ~i_flush ),
        .i_pop_bytes  ( 4'd1 ),
        .o_pop_ready ( queue_pop_ready ),
        .o_window_data( uop_queue_data ),
        .o_count      ( queue_count ),
        .o_full       ( queue_full ),
        .o_empty      ( queue_empty ),
        .clk          ( clk ),
        .rst_n        ( rst_n )
    );

    // ============================================================
    // Queue data assignment for push
    // ============================================================
    assign uop_queue_data[0] = uop_data_vector;

    // ============================================================
    // Queue output assignment
    // ============================================================
    assign uop_queue_out = uop_queue_data[0];
    assign uop_from_queue = uop_queue_out;
    assign queue_valid = ~queue_empty;

    // ============================================================
    // Pipeline register: uop_to_exu (stage 3 → stage 4_reg_read)
    // ============================================================
    uop_to_exu u_pipe_reg (
        .i_uop_valid   ( queue_valid          ),
        .i_uop         ( uop_from_queue       ),
        .i_exu_ready   ( i_stage4_ready       ),
        .o_stage3_ready( pipe_stage3_ready    ),
        .o_uop_valid   ( o_stage_valid        ),
        .o_uop         ( o_uop                ),
        .i_flush       ( i_flush              ),
        .clk           ( clk                  ),
        .rst_n         ( rst_n                )
    );

    // ============================================================
    // Output assignments
    // ============================================================
    assign o_stage2_ready = ~queue_full;

endmodule
